name: Issue / PR - Add to project

on:
  issues:
    types:
      - labeled
      - unlabeled
      - milestoned
      - demilestoned
  pull_request:
    types:
      - labeled
      - unlabeled
    branches:
      - '*'
  workflow_call: {}

defaults:
  run:
    shell: bash

jobs:
  add-to-project:
    name: Add to project
    permissions:
      repository-projects: write
      discussions: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Add to project
        id: add-to-project
        run: |
          echo "Event infos"
          echo " github.event.action                                      ${{ github.event.action }}" - labeled / unlabeled
          echo " github.event.assignee.login                              ${{ github.event.assignee.login }}"
          echo " github.event.assignee.email                              ${{ github.event.assignee.email }}"
          echo " github.event.assignee.type                               ${{ github.event.assignee.type }}"
          echo " github.event.project.name                                ${{ github.event.project.name }}"

          echo " github.event.issue.active_lock_reason                    ${{ github.event.issue.active_lock_reason }}"
          echo " github.event.issue.assignee.login                        ${{ github.event.issue.assignee.login }}"
          echo " github.event.issue.assignees[0].login                    ${{ github.event.issue.assignees[0].login }}"
          echo " github.event.issue.author_association                    ${{ github.event.issue.author_association }}"
          echo " github.event.issue.draft                                 ${{ github.event.issue.draft }}"
          echo " github.event.issue.labels.name                           ${{ github.event.issue.labels.name }}"
          echo " github.event.issue.labels[0].name                        ${{ github.event.issue.labels[0].name }}"
          echo " github.event.issue.labels_url                            ${{ github.event.issue.labels_url }}"
          echo " github.event.issue.locked                                ${{ github.event.issue.locked }}"
          echo " github.event.issue.milestone.title                       ${{ github.event.issue.milestone.title }}"
          echo " github.event.issue.milestone.due_on                      ${{ github.event.issue.milestone.due_on }}"
          echo " github.event.issue.milestone.state                       ${{ github.event.issue.milestone.state }}"
          echo " github.event.issue.milestone.open_issues                 ${{ github.event.issue.milestone.open_issues }}"
          echo " github.event.issue.number                                ${{ github.event.issue.number }}"
          echo " github.event.issue.reactions.confused                    ${{ github.event.issue.reactions.confused }}"
          echo " github.event.issue.reactions['+1']                       ${{ github.event.issue.reactions['+1'] }}"
          echo " github.event.issue.reactions['-1']                       ${{ github.event.issue.reactions['-1'] }}"
          echo " github.event.issue.reactions.total_count                 ${{ github.event.issue.reactions.total_count }}"
          echo " github.event.issue.reactions.rocket                      ${{ github.event.issue.reactions.rocket }}"
          echo " github.event.issue.sub_issues_summary.total              ${{ github.event.issue.sub_issues_summary.total }}"
          echo " github.event.issue.sub_issues_summary.completed          ${{ github.event.issue.sub_issues_summary.completed }}"
          echo " github.event.issue.sub_issues_summary.percent_completed  ${{ github.event.issue.sub_issues_summary.percent_completed }}"
          echo " github.event.issue.state                                 ${{ github.event.issue.state }}"
          echo " github.event.issue.state_reason                          ${{ github.event.issue.state_reason }}"
          echo " github.event.issue.title                                 ${{ github.event.issue.title }}"
          echo " github.event.issue.updated_at                            ${{ github.event.issue.updated_at }}"
          echo " github.event.issue.user.login                            ${{ github.event.issue.user.login }}"

          echo " github.event.pull_request._links.issue.href              ${{ github.event.pull_request._links.issue.href }}"
          echo " github.event.pull_request._links.self.href               ${{ github.event.pull_request._links.self.href }}"
          echo " github.event.pull_request.additions                      ${{ github.event.pull_request.additions }}"
          echo " github.event.pull_request.active_lock_reason             ${{ github.event.pull_request.active_lock_reason }}"
          echo " github.event.pull_request.assignee.login                 ${{ github.event.pull_request.assignee.login }}"
          echo " github.event.pull_request.assignees[0].login             ${{ github.event.pull_request.assignees[0].login }}"
          echo " github.event.pull_request.author_association             ${{ github.event.pull_request.author_association }}"
          echo " github.event.pull_request.draft                          ${{ github.event.pull_request.draft }}"
          echo " github.event.pull_request.base.ref                       ${{ github.event.pull_request.base.ref }}"
          echo " github.event.pull_request.base.label                     ${{ github.event.pull_request.base.label }}"
          echo " github.event.pull_request.base.repo.name                 ${{ github.event.pull_request.base.repo.name }}"
          echo " github.event.pull_request.base.repo.owner.login          ${{ github.event.pull_request.base.repo.owner.login }}"
          echo " github.event.pull_request.base.user                      ${{ github.event.pull_request.base.user }}"
          echo " github.event.pull_request.changed_files                  ${{ github.event.pull_request.changed_files }}"
          echo " github.event.pull_request.comments                       ${{ github.event.pull_request.comments }}"
          echo " github.event.pull_request.commits                        ${{ github.event.pull_request.commits }}"
          echo " github.event.pull_request.deletions                      ${{ github.event.pull_request.deletions }}"
          echo " github.event.pull_request.head.ref                       ${{ github.event.pull_request.head.ref }}"
          echo " github.event.pull_request.head.label                     ${{ github.event.pull_request.head.label }}"
          echo " github.event.pull_request.head.repo.name                 ${{ github.event.pull_request.head.repo.name }}"
          echo " github.event.pull_request.head.repo.owner.login          ${{ github.event.pull_request.head.repo.owner.login }}"
          echo " github.event.pull_request.head.user                      ${{ github.event.pull_request.head.user }}"
          echo " github.event.pull_request.issue_url                      ${{ github.event.pull_request.issue_url }}"
          echo " github.event.pull_request.labels.name                    ${{ github.event.pull_request.labels.name }}"
          echo " github.event.pull_request.labels[0].name                 ${{ github.event.pull_request.labels[0].name }}"
          echo " github.event.pull_request.labels_url                     ${{ github.event.pull_request.labels_url }}"
          echo " github.event.pull_request.locked                         ${{ github.event.pull_request.locked }}"
          echo " github.event.pull_request.maintainer_can_modify          ${{ github.event.pull_request.maintainer_can_modify }}"
          echo " github.event.pull_request.mergeable                      ${{ github.event.pull_request.mergeable }}"
          echo " github.event.pull_request.mergeable_state                ${{ github.event.pull_request.mergeable_state }}"
          echo " github.event.pull_request.merged                         ${{ github.event.pull_request.merged }}"
          echo " github.event.pull_request.merged_at                      ${{ github.event.pull_request.merged_at }}"
          echo " github.event.pull_request.merged_by.login                ${{ github.event.pull_request.merged_by.login }}"
          echo " github.event.pull_request.milestone.title                ${{ github.event.pull_request.milestone.title }}"
          echo " github.event.pull_request.milestone.due_on               ${{ github.event.pull_request.milestone.due_on }}"
          echo " github.event.pull_request.milestone.state                ${{ github.event.pull_request.milestone.state }}"
          echo " github.event.pull_request.milestone.open_issues          ${{ github.event.pull_request.milestone.open_issues }}"
          echo " github.event.pull_request.number                         ${{ github.event.pull_request.number }}"
          echo " github.event.pull_request.rebaseable                     ${{ github.event.pull_request.rebaseable }}"
          echo " github.event.pull_request.requested_reviewers[0].login   ${{ github.event.pull_request.requested_reviewers[0].login }}"
          echo " github.event.pull_request.requested_teams[0].name        ${{ github.event.pull_request.requested_teams[0].name }}"
          echo " github.event.pull_request.review_comments                ${{ github.event.pull_request.review_comments }}"
          echo " github.event.pull_request.state                          ${{ github.event.pull_request.state }}"
          echo " github.event.pull_request.state_reason                   ${{ github.event.pull_request.state_reason }}"
          echo " github.event.pull_request.title                          ${{ github.event.pull_request.title }}"
          echo " github.event.pull_request.updated_at                     ${{ github.event.pull_request.updated_at }}"
          echo " github.event.pull_request.user.login                     ${{ github.event.pull_request.user.login }}"

          echo " github.repository_owner                                  ${{ github.repository_owner }}"
          echo " github.repository                                        ${{ github.repository }}"
          echo " github.triggering_actor                                  ${{ github.triggering_actor }}"
          echo " github.ref_name                                          ${{ github.ref_name }}"
