name: Issue / PR - Add to project

on:
  issues:
    types:
      - labeled
      - unlabeled
      - milestoned
      - demilestoned
  workflow_call: {}

defaults:
  run:
    shell: bash

jobs:
  report-stale-branches:
    name: Report stale branches
    permissions:
      repository-projects: write
      discussions: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Add to project
        id: add-to-project
        run: |
          echo "Event infos"
          echo "${{ github.event.action }}"
          echo "${{ github.event.assignee.login }}"
          echo "${{ github.event.assignee.email }}"
          echo "${{ github.event.assignee.type }}"
          echo "${{ github.event.project.name }}"
          echo "${{ github.event.issue.active_lock_reason }}"
          echo "${{ github.event.issue.assignee.login }}"
          echo "${{ github.event.issue.assignees[0].login }}"
          echo "${{ github.event.issue.author_association }}"
          echo "${{ github.event.issue.draft }}"
          echo "${{ github.event.issue.labels.name }}"
          echo "${{ github.event.issue.labels[0].name }}"
          echo "${{ github.event.issue.labels_url }}"
          echo "${{ github.event.issue.locked }}"
          echo "${{ github.event.issue.milestone.title }}"
          echo "${{ github.event.issue.milestone.due_on }}"
          echo "${{ github.event.issue.milestone.state }}"
          echo "${{ github.event.issue.milestone.open_issues }}"
          echo "${{ github.event.issue.number }}"
          echo "${{ github.event.issue.reactions.confused }}"
          echo "${{ github.event.issue.reactions.'+1' }}"
          echo "${{ github.event.issue.reactions.'-1' }}"
          echo "${{ github.event.issue.reactions.total_count }}"
          echo "${{ github.event.issue.reactions.rocket }}"
          echo "${{ github.event.issue.sub_issues_summary.total }}"
          echo "${{ github.event.issue.sub_issues_summary.completed }}"
          echo "${{ github.event.issue.sub_issues_summary.percent_completed }}"
          echo "${{ github.event.issue.state }}"
          echo "${{ github.event.issue.state_reason }}"
          echo "${{ github.event.issue.title }}"
          echo "${{ github.event.issue.updated_at }}"
          echo "${{ github.event.issue.user.login }}"
          echo "${{ github.repository_owner }}"
          echo "${{ github.repository }}"
          echo "${{ github.triggering_actor }}"
          echo "${{ github.ref_name }}"
