name: Issue / PR - Add to project

on:
  issues:
    types:
      - labeled
      - unlabeled
      - milestoned
      - demilestoned
  workflow_call: {}

defaults:
  run:
    shell: bash

jobs:
  report-stale-branches:
    name: Report stale branches
    permissions:
      repository-projects: write
      discussions: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Add to project
        id: add-to-project
        run: |
          echo "Event infos"
          echo " github.event.issue.number             ${{ github.event.issue.number }}"
          echo " github.event.action                   ${{ github.event.action }}"
          echo " github.event.label.name               ${{ github.event.label.name }}"
          echo " github.event.issue.milestone.title    ${{ github.event.issue.milestone.title }}"
          echo " github.event.issue.labels             ${{ github.event.issue.labels }}"
          echo " github.event.issue.user               ${{ github.event.issue.user }}"
          echo " github.event.project.name             ${{ github.event.project.name }}"
          echo " github.event.issue.assignees          ${{ github.event.issue.assignees }}"
          echo " github.event.issue.assignee           ${{ github.event.issue.assignee }}"
          echo " github.event.issue.author_association ${{ github.event.issue.author_association }}"
          echo " github.event.issue.state              ${{ github.event.issue.state }}"
          echo " github.event.issue.state_reason       ${{ github.event.issue.state_reason }}"
          echo " github.repository_owner               ${{ github.repository_owner }}"
          echo " github.repository_owner               ${{ github.repository_owner }}"
